# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@mci.sankuai.com:mobile/DPPods.git'

target 'SDWebImageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'SDWebImage', :path => '../../sdwebimagecopy/SDWebImage.podspec'

  # Pods for SDWebImageDemo

end
